### ISSUE TITLE
Consent Cookie changes

### ISSUE THREAD

**Issue by DirkPersky** [davide-alghi/typo3-cookieconsent-plus#1]
He David,

thank you for your work.

With the last release `1.2.1` and `1.4.0` I completely rewritten the cookie banner.
As a result the cookie format has changed slightly.

The cookie "cookieconsent_status" has been removed.
The "dp_cookieconsent_status" cookie has a new format:

If the consent is open:
```json
{"status":"open", ....}
```

If the consent is approved/closed:
```json
{"status":"approved","checkboxes":[{"name":"statistics","checked":true},{"name":"marketing","checked":false}]}
```

Greetings
Dirk

**Comment by davide-alghi** [comment]
Hi @DirkPersky,
thank you very much for your information, you're very kind.
I'll test my ext with your last versions and I'll release new versions for old "behaviour" and the new one.
PS: in your issue content, I assume you meant your versions `11.2.1 and 11.4.0`

**Comment by DirkPersky** [comment]
Right, with 1.4.0 i rewritte the cookie code, and done a additonal release for older TYPO3 Version (1.2.1)

**Comment by davide-alghi** [comment]
Hi Dirk, Happy New Year.
Please can you confirm that, in the new version, the "mandatory" option is always "true"?

PS I have opted for a single version, compatible with both behaviors of dp_cookieconsent.
```PHP
$result = false;
if (\version_compare($version, '11.2.1', '==') || \version_compare($version, '11.4.0', '>=')) {
    $result = true;
}
```

**Comment by DirkPersky** [comment]
The mandatory checkbox is always true, as before, and it wouldn't passed to the Cookie,. 
Only the Boolean for statistics and marketing is passed to the cookie.

```json
{"status":"approved","checkboxes":[{"name":"statistics","checked":true},{"name":"marketing","checked":true}]}
```

![image](https://user-images.githubusercontent.com/1736266/147962472-56f3e7dc-4d1e-475e-b163-a2d6c29a707e.png)

happy new year too.
Dirk

ps: If you have some Italy translation, or any other i can add it to the [base translation](https://github.com/DirkPersky/npm-dp_cookieconsent/tree/master/src/js/l10n) if you want.

**Comment by davide-alghi** [comment]
in my (old version) extension I considered "Mandatory" cookies as "not accepted" if the user chose "Deny"

> ps: If you have some Italy translation, or any other i can add it to the [base translation](https://github.com/DirkPersky/npm-dp_cookieconsent/tree/master/src/js/l10n) if you want.

oh yes, I review the translations on your new version and send them to you

**Comment by davide-alghi** [comment]
Hi Dirk, attached the IT translation of all dp_cookieconsent lang files.

[dp_cookieconsent_translation.zip](https://github.com/davide-alghi/typo3-cookieconsent-plus/files/7827765/dp_cookieconsent_translation.zip)

PS I would be very pleased to include the German version in my ext: if you want I can attach the files to be translated :grin:

**Comment by DirkPersky** [comment]
Hey thanks very much for your support.
Sure i can help you with the german translation.

**Comment by davide-alghi** [comment]
Hi, tnx so much Dirk :thumbsup:
attached XLIFF files for my ext ... thanks for your support

[cookieconsent-plus_translation.zip](https://github.com/davide-alghi/typo3-cookieconsent-plus/files/7830571/cookieconsent-plus_translation.zip)
